name: melloddy_tuner
channels:
  - rdkit
  - defaults
  - conda-forge 
dependencies:
  - mkl=2019.4
  - mkl_random=1.0.2
  - numpy=1.16.5
  - openssl=1.1.1d
  - pandas=0.25.1
  - pip=19.2.2
  - python=3.6.9
  - rdkit=2019.03.4.0
  - scipy=1.3.1
  - sqlite=3.29.0
  - tqdm=4.32.1
  - nose2
  - pytest

